### ISSUE TITLE
alert button is smaller than submit/normal button

### ISSUE THREAD

**Issue by the-red** [kintone-labs/kintone-ui-component#1172]
## Version

- kintone-ui-component v1.5.0

## Environment

- Operating System: macOS 12.5.1
- Browser: Chrome 105.0.5195.125
- Node.js version: v14.18.1

## Current Behavior

タイプalertを使ってボタンを赤くすると、
submit, normalに比べてボタンが一回り小さくなってしまうのですが、
これは意図してこうなっているのでしょうか？

<img width="457" alt="CleanShot 2022-09-22 at 16 35 25@2x" src="https://user-images.githubusercontent.com/4494300/191686325-113d21df-3907-4a25-a2a4-2abba9f3660a.png">

developer toolsで確認してみると、こちらがsubmitのもので、
<img width="233" alt="CleanShot 2022-09-22 at 16 35 49@2x" src="https://user-images.githubusercontent.com/4494300/191686385-d9f19c47-765b-4d60-96cf-081729e7e2de.png">

こちらがalertです。`border`が消えてしまって、その枠の分が小さく見えてしまうようです。
<img width="207" alt="CleanShot 2022-09-22 at 16 36 07@2x" src="https://user-images.githubusercontent.com/4494300/191686442-607c70f5-f452-4c6a-8d74-cc246848a7f0.png">

## Expected Behavior

並べて表示するとかなり気になってしまうので、
全く同じサイズ感になるようにしてもらいたいです。

しかし、何か意図があってalertだけ小さくなっているのでしょうか？
もし理由があれば教えて下さい。

よろしくお願いします。

**Comment by TomokoMiyake** [comment]
@the-red 
確認が遅くなり申し訳ありません。
issue の登録をありがとうございます。

kintone の UI を参考に作っていますが、この border の差分は必要ない可能性が高そうです。
type ごとに CSS を充てているので、改めて確認したいと思います。

**Comment by the-red** [comment]
@TomokoMiyake 
よろしくお願いしますー！

kintone本体側の仕様と今はピッタリ合っているのかもしれませんが、
ui-componentとしては「自分でボタンを並べたときに綺麗に見えるように」という点を重視して、
kintoneの完コピにはこだわらないで頂きたいです。

**Comment by TomokoMiyake** [comment]
@the-red 
現状でも kintone 本体を基本参考にして実装していますが、完コピではないです。
コンポーネントとしての統一感が大事だと思いますので、その点は引き続き気をつけて実装していきます。
今回は border 部分の差分をケアできていなかったので、改善検討させていただきます。
ご意見ありがとうございます。

**Comment by TomokoMiyake** [comment]
@the-red 
お待たせしました。
上記について、修正版をリリースしました。Button type ごとの不要な差分を削除して統一しております。
ご確認いただけると嬉しいです。
https://github.com/kintone-labs/kintone-ui-component/releases/tag/v1.7.0

**Comment by TomokoMiyake** [comment]
@the-red 
上記の通り修正済みのため、こちらの issue をクローズしても問題ないでしょうか？

**Comment by the-red** [comment]
@TomokoMiyake 
返信できてなくてすみません！
まだ確認はできてないのですが、直していただけたということでありがとうございます！
closeしておきますねー。

今後もいろいろ楽しみにしてます！

**Comment by TomokoMiyake** [comment]
@the-red 
こちらこそ確認が遅れました。
close ありがとうございました！

楽しみにしていただけて嬉しいです。
