### ISSUE TITLE
react@18  Could not resolve dependency

### ISSUE THREAD

**Issue by master-maintenance1-peer-connect** [kintone-labs/kintone-ui-component#1269]
could not be used with react@18.

## Version
- @kintone/kintone-ui-component v0.9.3

## Environment

- Operating System: windows10
- Browser: edge
- Node.js version: v16.18.0

## Current Behavior

```
npm update

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: monthly_totals4gruops@0.3.2
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from @kintone/kintone-ui-component@0.9.3
npm ERR! node_modules/@kintone/kintone-ui-component
npm ERR!   @kintone/kintone-ui-component@"^0.9.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## Expected Behavior
  The use of react@17 will also be deprecated soon, 
so we expect to be able to use kintone-ui-component with react@18 or later.

**Comment by TomokoMiyake** [comment]
@master-maintenance1-peer-connect 
Thank you for the issue.
We will check the contents and reply to you.
Please wait a moment.

**Comment by TomokoMiyake** [comment]
@master-maintenance1-peer-connect 
We checked our project status and decided not to upgrade to React18 now.
Sorry for the inconvenience.

Here is the reason why.
- We couldn't find any official info that React17 will be deprecated soon.
- If we upgrade to React18, the users who are currently using the kintone UI Component v0 may not be able to use it after upgrading the package.
- We are planning to stop maintenance of kintone UI Component v0 within 2023 as we described below. (*you can see the info in the "Other" category of Roadmap)
  https://github.com/kintone-labs/kintone-ui-component/discussions/987

**Comment by TomokoMiyake** [comment]
@master-maintenance1-peer-connect 
After the confirmation above, please close the issue if you can.

Thank you!
