### ISSUE TITLE
Hide table header

### ISSUE THREAD

**Issue by the-red** [kintone-labs/kintone-ui-component#1333]
## Component

Table

## Why

テーブル内にテーブルをネストしたいことがあります。
その場合、内側のヘッダーが悪目立ちしてしまいます。

<img width="1478" alt="CleanShot 2023-05-09 at 14 11 27@2x" src="https://user-images.githubusercontent.com/4494300/236999896-0c69544f-eba2-4293-9a80-eae051ec3a52.png">

内側はヘッダーではなくPlaceholderを使ってこんな風にしたいです。
自分でhackすれば出来ますが、標準機能でヘッダーを非表示にできると嬉しいです。

<img width="1464" alt="CleanShot 2023-05-09 at 14 16 05@2x" src="https://user-images.githubusercontent.com/4494300/237000469-f0e3d40b-9489-4cdc-ab25-fb02662ec52f.png">

## What

Boolean型の`header`プロパティなど如何でしょうか？

```js
const table = new Kuc.Table({
  header: false, // 省略したらtrue
  columns: [
      {
        title: 'Name',
        field: 'name',
        render: renderName
      },
      {
        title: 'Address',
        field: 'address'
      },
      {
        title: 'Age',
        field: 'age',
        render: renderAge
      }
    ],
  data: [
    {
      name: 'john',
      age: 32,
      address: 'New York No. 1 Lake Park'
    },
    {
      name: 'steven',
      age: 22,
      address: 'New York No. 2 Lake Park'
    }
  ],
})
```

ご検討お願いします！

**Comment by TomokoMiyake** [comment]
@the-red 
新機能のアイデア登録ありがとうございます。
1st リリースでは要件から落としましたが、今後の対応要件として検討していたものになります。
前向きに検討させていただきます。

**Comment by TomokoMiyake** [comment]
@the-red 
`headerVisible` property の実装中になります。次のリリースで提供予定です。

**Comment by TomokoMiyake** [comment]
@the-red 
We release v1.12.0 which includes the headerVisible property you requested above.
https://github.com/kintone-labs/kintone-ui-component/releases/tag/v1.12.0

Thank you!
