### ISSUE TITLE
Disabling items

### ISSUE THREAD

**Issue by miko-hirai** [kintone-labs/kintone-ui-component#1348]
I would like to have the capability to disable individual items within the MultipleChoice and CheckBox components,similar to how it was implemented in v0 using the options.items[x].isDisabled parameter.

**Comment by miko-hirai** [comment]
There are many cases where the values of checkboxes or multiple selections need to be dynamically disabled.
https://cybozudev.zendesk.com/hc/ja/articles/360000511023--kintone-UI-Component-v0-%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E7%B0%A1%E5%8D%98%E3%81%ABkintone%E3%83%A9%E3%82%A4%E3%82%AF%E3%81%AAUI%E3%82%92%E8%A8%AD%E7%BD%AE%E3%81%99%E3%82%8B#step3

**Comment by TomokoMiyake** [comment]
@miko-hirai 
Thank you for the example.
We will consider the `disabled` feature for individual items on selection type components.

**Comment by TomokoMiyake** [comment]
@miko-hirai 
We are planning to release the `disabled` property for individual items on selection-type components in the next release.
Please wait for the updates.

Thank you!

**Comment by TomokoMiyake** [comment]
@miko-hirai 
Hi, we just released v1.13.0 including your request above.
Please check the latest version here.
https://github.com/kintone-labs/kintone-ui-component/releases/tag/v1.13.0

We developed `disabled` property for each item on several selection-type components.

If it meets your intention, please close this issue, too.

Thank you for your request this time!

**Comment by TomokoMiyake** [comment]
@miko-hirai 
I'm sorry about the repeated comment!
Can we close this issue now?

**Comment by TomokoMiyake** [comment]
I closed this issue because we have already released the requested content.
If you have any further opinions, please register a new one.

Thank you!!
