### ISSUE TITLE
Attachment display switching is locked.

### ISSUE THREAD

**Issue by motohasystem** [kintone-labs/kintone-ui-component#1533]
AttachmentコンポーネントにDnDしようとしたとき、ファイルを抱えたマウスカーソルをコンポーネントの左側から侵入させると、たまに表示切替がロックされてしまうことがあります。

https://github.com/kintone-labs/kintone-ui-component/assets/2771525/3e838da0-2596-4f8b-8b1e-b899d0f02123

ブラウザを切り替えて試したところ、Firefoxでは発生しますが、Chromeでは再現しませんでした。
Firefox限定の不具合なのかもしれません。

**Comment by TomokoMiyake** [comment]
@motohasystem 
issue 登録ありがとうございます。
こちら現象を確認してご連絡させていただきます。少しお時間頂戴するかもしれません。

**Comment by TomokoMiyake** [comment]
@motohasystem 
登録いただいた現象について、開発チームでも再現しました。
Firefox のみ以下の事象が起きています。
- ドラッグ&ドロップを何度か繰り返していると、時々表示切り替えがロックされる（左右上下いずれからの操作でも起きるが、特に左からのアップロード操作ができなくなることが多い）
- 一度表示切り替えがロックされると、左右上下いずれからもドラッグ&ドロップでのアップロードができなくなる

Attachment コンポーネントの主要な操作ができなくなる事象なので、パッチバージョンのリリースを計画しています。
修正・リリース作業のためしばらくお待ちいただくことになるかと思いますが、ご了承ください。

また気になる点などございましたら、お気軽にご連絡いただけると幸いです。

**Comment by TomokoMiyake** [comment]
@motohasystem 
This issue was resolved, so I will close this issue.

Thank you!
