### ISSUE TITLE
[Resolved] CDN is down and the component pages of the user guide are crashed and cannot be accessed

### ISSUE THREAD

**Issue by erikotaniguchi** [kintone-labs/kintone-ui-component#1534]
This is the issue registration from the kintone UI Component development team.
We found that the CDN is not available now due to the [unpkg issue](https://github.com/mjackson/unpkg/issues/384).
https://unpkg.com/kintone-ui-component/umd/kuc.min.js

And due to that, the component pages of the user guide are crashed and cannot be accessed.
https://ui-component.kintone.dev/docs/components/desktop/attachment
<img width="1047" alt="kuc user guide" src="https://github.com/kintone-labs/kintone-ui-component/assets/15206920/6a8dd188-c92a-4c18-8183-651d8ed2c9cf">

We are waiting for unpkg side to find the cause and recovery.
We apologize for any inconveniences this may cause.

**Comment by TomokoMiyake** [comment]
The above issue is resolved now.
Sorry for the inconvenience.
