### ISSUE TITLE
Attachment component label property doesn't work

### ISSUE THREAD

**Issue by yahataka** [kintone-labs/kintone-ui-component#1546]
## Version

- kintone-ui-component v1.17.1

## Environment

- Operating System: windows10
- Browser: Firefox, Chrome
- Node.js version: v20.9.0

## Current Behavior

  When I import the Attachment component directly via lib as shown below, the labal property does not work.

==============script==============
import { Attachment } from "kintone-ui-component/lib/attachment";
//import { Attachment } from "kintone-ui-component";

(function () {
  kintone.events.on("app.record.index.show", (event) => {
    const attach = new Attachment({ label: "test", id: "attach" });
    const space = kintone.app.getHeaderSpaceElement();
    space?.appendChild(attach);
  });
})();

**Comment by yfang-cybozu** [comment]
we will check and reply to you ASAP.

**Comment by TomokoMiyake** [comment]
@yahataka 
We have reproduced the issue and found that this issue will occur on another component.
Here are the cases.

Case 1
When importing in this way for Attachment component, label and error cannot be used.
import { Attachment } from "kintone-ui-component/lib/attachment";

Case2
When importing in this way for MobileDateTimePicker, label and error cannot be used.
import { MobileDateTimePicker } from "kintone-ui-component/lib/mobile/datetime-picker";

We will fix it in the future version.
So until the next release, please use `import { Attachment } from "kintone-ui-component";` way of importing.
Sorry for the inconvenience.

**Comment by erikotaniguchi** [comment]
@yahataka 
We released v1.18.0 including this issue you reported.
https://github.com/kintone-labs/kintone-ui-component/releases/tag/v1.18.0
Thank you!

**Comment by erikotaniguchi** [comment]
This issue was resolved, so I will close this issue.
Thank you!
