### ISSUE TITLE
 I want to use in reading mode.

### ISSUE THREAD

**Issue by cy-takeuchi** [kintone-labs/kintone-ui-component#32]
例えば詳細画面でテーブル表示したい場合があります。
その際に表示しても入力モードになるので閲覧モードのようなものを追加して欲しいです。

For example, I want to display a table on the detail screen.
Since it becomes input mode even if it displays at that time, I want something like reading mode to be added.

**Comment by TomokoMiyake** [comment]
@cy-takeuchi 
We are now considering the Table component for edit and read mode for v1.
Please look forward to it.

Always thank you for the feedback.
