### ISSUE TITLE
I cannot update isDisabled in table.updateRowData

### ISSUE THREAD

**Issue by miko-hirai** [kintone-labs/kintone-ui-component#434]
テーブルに配置したテキストボックスやドロップダウンボックスを
isDisabled = trueにて無効にしたいのですが、updateRowData()にて
反映することができません。valueは更新されます。
setValue()の場合は、想定どおり、valueの更新及び要素が無効になります。

https://kintone.github.io/kintone-ui-component/latest/Reference/Table/
上記の一番最初に掲載されているサンプルソースに以下のコードを
追加して試行しました。

  var button = new kintoneUIComponent.Button({text: 'button'});
  var body = document.getElementsByTagName("BODY")[0];
  body.appendChild(button.render());
  button.on('click', function(event) {
    var value = table.getValue();
    value[0].text.isDisabled = true;
    value[0].text.value = 'update test!!!';
    value[0].toys.isDisabled = true;
    value[0].toys.items[3] = {label: "block", value: "block", isDisabled: false};
    table.updateRowData(0, value[0]);　// →text.valueやtoys.itemsは更新されるが、isDisabledは画面に反映されない。
    // table.setValue(value);　　　　　// →　valueもisDisabledも正常に変更できる。
  });

ご確認よろしくお願い致します。

**Comment by kkawataki** [comment]
issueの登録ありがとうございます。
お問い合わせいただいた内容につきまして調査したところ、
こちらの検証環境で同様の事象が再現することを確認いたしました。

本事象は、kintone UI Component v0.7.2の仕様によるものです。
現行バージョンの仕様ですと、Tableの「updateRowData」メソッドにおいて更新の対象となっているプロパティは「items」「value」「text」のみで、「isDisabled」はこのメソッドでは更新されません。
そのため、「isDisabled」を更新したい場合は、「setValue」メソッドをお使いください。
ご不便おかけしますが、よろしくお願いいたします。

**Comment by miko-hirai** [comment]
ご返答ありがとうございます。
以前のバージョンではisDisabledの更新も可能だったと思うのですが、機能を落とされたのは理由があるのでしょうか。
今後のバージョンアップで対応の予定はありますか。

**Comment by kkawataki** [comment]
先日の回答ですが、1点訂正させていただきます。
お問い合わせいただいた事象について、kintone UI Component v0.7.2の仕様によるものとお答えしましたが、
改めて調査した結果、不具合であることがわかりました。誤案内となり申し訳ございません。
こちらにつきましては、今後のアップデートで対応を検討させていただきます。

ご認識されている「setValue」を使用することで「isDisabled」の更新が可能となっていますので、
現行バージョンにおいてはそちらを使用いただければと思います。

**Comment by TomokoMiyake** [comment]
@miko-hirai 
大変お待たせいたしました。
本不具合は先ほどリリースしました v0.7.8 にて修正いたしました。
https://github.com/kintone-labs/kintone-ui-component/releases/tag/v0.7.8

updateRowData を使って、Table コンポーネントの各行の isDisabled プロパティの状態を更新できるようになりました。
ご確認よろしくお願いいたします。

-------
We have fixed this bug in v0.7.8.
https://github.com/kintone-labs/kintone-ui-component/releases/tag/v0.7.8

Now you can use the function updateRowData for updating the status of the property (isDisabled) on any rows of the Table Component.
Thank you!
