### ISSUE TITLE
Set blank(or null) value to date component.

### ISSUE THREAD

**Issue by Yanchi4425** [kintone-labs/kintone-ui-component#436]
I want to set blank(or null) value to date component.
However, setting null or undefined in the date component will result in an error.

Therefore, such a writing will cause an error :

```
const [date, setDate] = useState(null);
// => Locale.js:102 TypeError: Cannot read property 'getMilliseconds' of null

// const [date, setDate] = useState(undefined);
// => The current date and time is set. but, it freezes when focused.

// const [date, setDate] = useState('');
// => TypeError: dirtyDate.getMilliseconds is not a function

return (
    <DateTime
           value={date}
           onChange={value => setDate(value)}
            type='datetime'
      />
);
```

Is there a way to empty the value?
I want to be able to set both date selection and time selection blank.

**Comment by kkawataki** [comment]
Thank you for inquiring.
Currently value of DateTime component can only be cleared by pressing [clear button].
So we' ll consider whether we correspond this issue in the next version of kintone UI Component.

**Comment by Yanchi4425** [comment]
Thanks for the reply.

It seems that pressing the clear button only clears the display and not the value.
Also, the time cannot be cleared.

I would like to see an update to this problem.

**Comment by trung-doan** [comment]
@Yanchi4425 
We have fixed this bug on [v0.8.0](https://github.com/kintone-labs/kintone-ui-component/releases/tag/v0.8.0)
Now, you can init/update DateTime component with "null" value for setting Date and Time as empty.
Please see more detail at [DateTime references](https://kintone-labs.github.io/kintone-ui-component/latest/Reference/DateTime/) .
Thank you!

**Comment by Yanchi4425** [comment]
@trung-doan 
Hi. Thank you for fixing.
Will v0 development and maintenance continue?

**Comment by TomokoMiyake** [comment]
@Yanchi4425 
Thank you for the question!
We will mainly develop v1 (add components and improve existing components).
For v0, we will continue the bug fix and library updates for a while.

**Comment by Yanchi4425** [comment]
Please tell me the latest way to install v0.8.0.

I tried this:

```
npm install git+https://github.com/kintone-labs/kintone-ui-component.git#v0.8.0
```

But, it seems that the v0.x.0 version was installed before this issue was applied.
Thank you.
