### ISSUE TITLE
kintone UI Component v1.0 release plan

### ISSUE THREAD

**Issue by miyass** [kintone-labs/kintone-ui-component#443]
# kuc v1 release plan

We have re-designed the framework inside and the interface for below.

- Design refinement
- Easier-to-use library
- Mobile Component support

## 1. Component list

Scheduled to be released in October 2020.

**Desktop**

- Button
- Checkbox
- Dialog
- Dropdown
- MultiChoice
- Notification
- RadioButton
- ReadOnlyTable
- Spinner
- Table
- Text
- TextArea

**Mobile**

- Button
- Checkbox
- RadioButton
- Text
- TextArea

We will develop other components' mobile version sequentially.

## 2. Component list to stop development

We will stop these components' development for now because there are few use cases.
If you have any use cases, please reach out to us. We will consider to correspond.

- Attachment
- ColorPicker
- FieldGroup
- IconButton
- Tab
- React ver.

## 3. Possible future development list

This is a list that we will not support in the v1 initial version,
but we would like to consider future support depending on the future feedback.

- Date
- DateTime
- Other Mobile components

**Comment by miyass** [comment]
Due to delays in development, we will be postponing the release of kuc v1.
The specific date has yet to be determined, but we will announce as soon as possible.
Thank you for your understanding.

**Comment by TomokoMiyake** [comment]
We released the v1.0.0 version of kintone UI Component.
https://github.com/kintone-labs/kintone-ui-component/releases/tag/v1.0.0

About the future plan, we will announce it on a new issue.
If you have feedback, please feel free to post an [issue](https://github.com/kintone-labs/kintone-ui-component/issues/new/choose).
