### ISSUE TITLE
Searchable dropdown list

### ISSUE THREAD

**Issue by the-red** [kintone-labs/kintone-ui-component#496]
## Component

I'd like a searchable drop-down list, like the "Datasource App" below.

![image](https://user-images.githubusercontent.com/4494300/112092643-47955600-8bdb-11eb-8ee9-9fd2929b6bbd.png)

## Why

The more items in the drop-down list, the harder it is to select them.
This can be achieved by using a library like "Select2", but I need something that matches the design of kintone.
https://select2.org/

### Idea1

Add a option like "search" to the Dropdown component.

```js
const dropdown = new Kuc.Dropdown({
  search: true,
  label: 'Fruit',
  requiredIcon: true,
  items: [
    {
      label: 'orange',
      value: 'Orange'
    },
    {
      label: 'apple',
      value: 'Apple'
    }
  ],
  value:  'Orange',
  error: 'Error occurred!',
  className: 'options-class',
  id: 'options-id',
  visible: true,
  disabled: false
});
```

### Idea2

Add a new component like "SearchableDropdown".

```js
const dropdown = new Kuc.SearchableDropdown({
  label: 'Fruit',
  requiredIcon: true,
  items: [
    {
      label: 'orange',
      value: 'Orange'
    },
    {
      label: 'apple',
      value: 'Apple'
    }
  ],
  value:  'Orange',
  error: 'Error occurred!',
  className: 'options-class',
  id: 'options-id',
  visible: true,
  disabled: false
});
```

**Comment by TomokoMiyake** [comment]
@the-red 
Thank you so much for the new idea registration!
It helps us a lot to consider the new functions.

Your idea seems reasonable and I could imagine the use cases of it easily.
We would like to consider it for the future version.

**Comment by TomokoMiyake** [comment]
@the-red 
We are working on the `Combobox` component development to achieve the idea above.
Please wait for the release of it.

Thank you!

**Comment by TomokoMiyake** [comment]
@the-red 
Today we published `Combobox` component that allows the user to find an item among many choices in v1.9.0.
Please utilize it.
https://github.com/kintone-labs/kintone-ui-component/releases/tag/v1.9.0

You can see the document here.
https://kintone-ui-component.netlify.app/docs/en/components/desktop/combobox

Thank you for your feedback!

**Comment by the-red** [comment]
@TomokoMiyake 
Excellent❗❗❗❗❗❗ 
Thank you 😄
