### ISSUE TITLE
Dropdown display collapses on group field.

### ISSUE THREAD

**Issue by juridon** [kintone-labs/kintone-ui-component#512]
If possible, please write the issue and pull-request in English.
But it's not an absolute rule. Japanese is ok.

## Version

- kintone-ui-component v1.0.2

## Environment

- Operating System: win 10
- Browser: chrome
- Node.js version:

## Current Behavior

Dropdown display collapses on group field.
(operation is nomal)

![image](https://user-images.githubusercontent.com/66515042/114662387-9003e780-9d33-11eb-809c-f8eee1cfc699.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/66515042/114662697-19b3b500-9d34-11eb-89ff-88b33c5be940.png)

**Comment by TomokoMiyake** [comment]
@juridon 
Thank you for the issue registration.
We will check and consider corresponding in the future version.

**Comment by trung-doan** [comment]
@juridon 
This issue has been fixed at [v1.0.4](https://github.com/kintone-labs/kintone-ui-component/releases/tag/v1.0.4)
Thank you!
