### ISSUE TITLE
To use v1 with React

### ISSUE THREAD

**Issue by Yanchi4425** [kintone-labs/kintone-ui-component#542]
## Component

> Which component do you want to add a feature for?

All components.

> What components do you want to add?

React supported component.

## Why

> Why do you want the feature and why does it make sense for kintone UI Component?

We are developing with React using kintone-cli.

## What

> What is a solution you want to add?

React compatible components or Please tell me how to use lit-element in React.

Here is a sample of the text component I thought of:

```tsx
import React from "react";
import { Text as KText} from "kintone-ui-component";

interface TextProps {
    disabled?:boolean;
    error?: string;
    id?: string;
    label?: string;
    placeholder?: string;
    prefix?: string;
    suffix?: string;
    textAlign?: "left" | "right";
    value: string
    requiredIcon?:boolean;
    visible?: boolean;
    onChange?: (event: any) => void;
    onFocus?: (event: any) => void;
}

const Text: React.VFC<TextProps> = (props: TextProps) => {
    return (
        <div
            style={{display:"inline-block"}}
            ref={(ref) => {
                // prevent rerendering
                if(!ref || ref.querySelectorAll("*").length > 0) return;

                const component = new KText(props);
                component.addEventListener("change", props.onChange);
                component.addEventListener("focus", props.onFocus);
                ref.appendChild(component);
            }}
        />
    );
}

const SameComponent = () => {
    const [text, setText] = useState<string>("");
    const [disable, setDisable] = useState(false);

    return <>
            <button onClick={() => setDisable(!disable)}>toggle disable</button>
            <Text
                value={text}
                onChange={ e => {
                    setText(e.detail.value);
                }}
                disabled={disable}
            />
    </>;
}
```

This sample can state manage the value, but cannot manage disabled.

**Comment by TomokoMiyake** [comment]
@Yanchi4425 
Thank you for the issue request!
At the moment, the priority is to add and improve the components of the JavaScript version, and we don't have a concrete plan to support the React version for now.
We apologize for not being able to respond to your request immediately.
If you want to develop components using React now, we would appreciate it if you could use v0.
If you have an additional question or request, please feel free to tell us.

Thank you.

**Comment by Yanchi4425** [comment]
Coding instructions will be shared in #936 , so this is closed.

**Comment by TomokoMiyake** [comment]
@Yanchi4425
We have just shared the "Using kintone UI Component in React" guide on Discussion.
Please check it.
https://github.com/kintone-labs/kintone-ui-component/discussions/990
