### ISSUE TITLE
Dropdowns can be selected even when disabled.

### ISSUE THREAD

**Issue by Yanchi4425** [kintone-labs/kintone-ui-component#553]
## Version

- @kintone/kintone-ui-component v0.8.0

## Environment

- Operating System: Windows 10
- Browser:  Google chrome 90.0.4430.93
- Node.js version: v12.18.2

## Current Behavior

The choices are displayed when you click the drop-down component with the isDisabled property set to "true".
And they won't disappear when you click outside or make a selection.

## Expected Behavior

If isDisabled = true, do not show the choices.

**Comment by trung-doan** [comment]
@Yanchi4425 
Thank for your feedback.
This issue will be occurred in React component and we will fix this bug in future version.

**Comment by trung-doan** [comment]
@Yanchi4425 
This issue has been fixed in [v0.8.1](https://github.com/kintone-labs/kintone-ui-component/releases/tag/v0.8.1)
Thank you!
