### ISSUE TITLE
[FeatureRequest] Set child element for the text property of the button component.

### ISSUE THREAD

**Issue by Yanchi4425** [kintone-labs/kintone-ui-component#956]
## Component

Button Component

## Why

We can display an icon (e.g. font-awasome) on the button component.

## What

Make it possible to add not only String but also HTML Element or tag string to the text property.

```
const icon = document.createElement("i");
icon.classList.add("fas");
icon.classList.add("fa-file");
const button = new Kuc.Button({
    text: icon,
});

// or 
const button = new Kuc.Button({
    text: `<i class="fas fa-file"><i>`,
});
```

**Comment by TomokoMiyake** [comment]
@Yanchi4425 
Thank you very much for the feature request.
Do you want to create this kind of icon button?
https://developer.cybozu.io/hc/ja/articles/208192343

**Comment by Yanchi4425** [comment]
@TomokoMiyake 
Sorry for the late reply.
Yes, I want to create such an icon button.

**Comment by TomokoMiyake** [comment]
@Yanchi4425 
Thank you for your reply.
I understand it.

**Comment by TomokoMiyake** [comment]
@Yanchi4425 
Hi!
Considering your idea above, now we are developing `content` property that can accept string/HTMLElement besides the existing `text` property to be able to add custom icons.
Please look forward to the next release.

Thank you!

**Comment by Yanchi4425** [comment]
@TomokoMiyake 
Hi!
Thank you for your reply. 

Unfortunately, I am no longer involved in the Kintone customization project, but I will provide this information to the team. 
I will continue to keep an eye on your project from time to time. 

Thanks!

**Comment by TomokoMiyake** [comment]
@Yanchi4425 
Thank you very much for your quick reply and notification to your team member!
I appreciate your contribution to our package.
Please keep in touch.

Here is the 2023 roadmap. This year, we will focus on improvement based on user feedback.
https://github.com/kintone-labs/kintone-ui-component/discussions/1287

Thank you!

**Comment by TomokoMiyake** [comment]
@Yanchi4425 
Hi.
We released a new version that included the `content` property and made it able to set custom elements in Button and MobileButton components.
For more detail, please check the release notes.
https://github.com/kintone-labs/kintone-ui-component/releases/tag/v1.11.0

Thank you for your feedback.
